# Generated by Django 4.2.21 on 2025-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVehiculos', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('MES', 'Mesero'), ('CLI', 'Cliente')], default='MES', max_length=3),
        ),
    ]
