# Generated by Django 4.2.21 on 2025-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVehiculos', '0003_alter_empleado_tipo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('MES', 'Mesero')], default='MES', max_length=3),
        ),
    ]
