services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gestion_vehiculos_db
      POSTGRES_USER: admin_vehiculos
      POSTGRES_PASSWORD: vehiculos123
      POSTGRES_HOST_AUTH_METHOD: trust  # ¡Nueva línea importante!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin_vehiculos:vehiculos123@db:5432/gestion_vehiculos_db

volumes:
  postgres_data: